### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by brianroesler** [WaterfallEngineering/SpookyJS#133]
I get the following error when I try to run the example...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

Just wondering if anyone can shed some light on what's going on.

Thanks!

**Comment by brianroesler** [comment]
Nvm, this was related to the latest version of PhantomJS not being compatible with the latest version of Yosemite.
