### ISSUE TITLE
hello.js fails on recent install

### ISSUE THREAD

**Issue by chrishiestand** [WaterfallEngineering/SpookyJS#134]
This is under OS X Yosemite 10.10.2

`git clone git@github.com:WaterfallEngineering/SpookyJS.git`
`cd SpookyJS`

`git rev-parse HEAD`
> 66b6c851177ae4eaadf843a469807866dabafbd2

`phantomjs --version`
> 1.9.8

`node --version`
> v0.12.0

`npm install`

`node examples/hello.js`
>undefined:1
><!DOCTYPE html>
>^
>SyntaxError: Unexpected token <
    at Object.parse (native)
    at StreamClient._onData (/private/tmp/SpookyJS/node_modules/tiny-jsonrpc/lib/tiny-jsonrpc/stream-client.js:85:25)
    at RequestStream.emit (events.js:107:17)
    at RequestStream.<anonymous> (/private/tmp/SpookyJS/lib/spooky/request-stream.js:47:14)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by chrishiestand** [comment]
`mocha tests/test`

>  the PhantomJS bootstrap script
    ✓ hooks phantom.onError to emit an error event and exit non-zero (1187ms)
    ✓ crashes if passed an unknown transport (1204ms)

>  bootstrap/emit
    ✓ provides emit, which emits an event (70ms)
    1) "before each" hook

>  3 passing (4s)
  1 failing

>  1) bootstrap/emit "before each" hook:
     Uncaught Error: Child terminated with non-zero exit code 1
      at Spooky.<anonymous> (/private/tmp/SpookyJS/lib/spooky.js:210:17)
      at ChildProcess.emit (events.js:110:17)
      at Process.ChildProcess._handle.onexit (child_process.js:1067:12)

**Comment by lawnsea** [comment]
Fun. I do not have Yosemite installed and will not be able to do so until our IT approves it.

```
undefined:1
<!DOCTYPE html>
```

This is odd. It looks like something is printing the HTML source to stdio.
